export enum TraitCategory {
    INTELLECTUAL = 'INTELLECTUAL',
    CREATIVE = 'CREATIVE',
    SOCIO_EMOTIONAL = 'SOCIO_EMOTIONAL',
    SENSORY = 'SENSORY',
    EXECUTIVE_FUNCTION = 'EXECUTIVE_FUNCTION',
}
